version: 2
jobs:
  build:
    working_directory: ~/python_package_template
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run: mkdir venv
      - run: 'sudo pip install -r ./test-requirements.txt --upgrade --force-reinstall'
      - run:
          name: Pylint
          command: 'pylint ./python_package_template/'

workflows:
  version: 2
  build_test:
    jobs:
      - build
