version: 2
jobs:
  linter:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "PyLint verification."

  py27:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Python 2.7 workflow."

  py38:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Python 3.8 workflow"

workflows:
  version: 2
  pipeline:
    jobs:
      - linter
      - py27
      - py38
